src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"title"},
 * message ="Une autre annonce a deja ce titre")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min =10, max = 100, minMessage = "votre titre doit depassez 10 caractere",
     * maxMessage = "votre titre ne doit pas depasse 100 caractere")
     * 
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, max=50, minMessage="Votre introduction doit depasse 20 caractere")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, max=150, minMessage="Votre description doit depasse 20 caractere")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'avoir le nombre de votes d'une annonces
     */
    public function getAvgRatings(){
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        },0);
       if(count($this->comments) >0) return  $sum / count($this->comments);
        return 0;
    }
    /**
     * permet de construire le slug de facon automatique
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initialise(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);

        }
    }
    /**
     * permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette formation
     *
     * @return array
     */
    public function getNotAvailabledays()
    {
        $notAvailableDays =[];
        foreach($this->bookings as $booking){
            $resultat =range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;

use App\Form\ImageType;
use App\Form \ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('title',TextType::class, $this->getinformation("Titre","Mettez un titre attirant"))
        ->add('slug',TextType::class, $this->getinformation("Slog","votre slog sera genere de facon automatique",
        ['required' => false]))
        ->add('price', MoneyType::class,  $this->getinformation("Prix par nuit","Mettez votre prix"))
        ->add('introduction',TextType::class, $this->getinformation("Introduction","Mettez une description annonce"))
        ->add('content', TextareaType::class, $this->getinformation("Description","Mettez un contenu"))
        ->add('coverImage',UrlType::class, $this->getinformation("Image","Mettez une image attirant"))
        ->add('rooms',IntegerType::class,$this->getinformation("Nombre de chambres","Mettez le nombre de chambres"))
        ->add('images', CollectionType::class,
        [
            'entry_type'=>ImageType::class,
            'allow_add' =>true,
            'allow_delete' =>true
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    
     /**
     * @Route("/ad/new", name="nouveau_annonce")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function new(Request $request, EntityManagerInterface $manager)
    {
        $ad = new Ad();
         $form = $this->createForm(AdType::class, $ad);
         $form->handleRequest($request);
         if($form->isSubmitted() && $form->isValid()){
             foreach($ad->getImages() as $image){
                 $image->setAd($ad);
                 $manager->persist($image);
             }
             $ad->setAuthor($this->getUser());
             $manager->persist($ad);
             $manager->flush();
            // $this->addFlash('success','Votre article à bien été enregistrer');
                 
             return $this->redirectToRoute('voir_annonce',[
                 'slug' => $ad->getSlug()
                 ]);
         }
        
        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
        
    }
    /**
     * @Route("/voirs", name="voirs_annonces")
     */
    public function index(AdRepository $rep)
    {
        $ads = $rep->findAll();
        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }
    /**
     *@Route("/ad/{slug}/edit", name="edite_article")
     *@Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message ="vous n'etez pas le proprietaire")
     * @return Response
     */
    public function edit(Ad $ad, EntityManagerInterface $manager, Request $request){
        $form = $this->createForm(AdType::class, $ad);

         $form->handleRequest($request);
         if($form->isSubmitted()&& $form->isValid()){
             foreach($ad->getImages() as  $image){
                 $image->setAd($ad);
                 $manager->persist($image);
             }
             $ad=$form->getData();
             $manager->persist($ad);
             $manager->flush();
             
             return $this->redirectToRoute('voir_annonce',[
                 'slug' => $ad->getSlug()
                 ]);
                 $this->addFlash(
                     'succes',
                     "les  Mofication ont ete effectuer"

                 );

         }
         

        return $this->render('ad/edit.html.twig',[
            'form'=>$form->createView(),
            'ad'=>$ad
        ]);
    }

    /**
     * @Route("/ad/{slug}", name="voir_annonce")
     * 
     * @return Response
     */
    public function voir(Ad $ad)
    {
        
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
        
    }
    /**
     * Undocumented function
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()")
     *@Route("article/supprimer/{slug}", name="supprimer_article")
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return void
     */
    public function delete_article(Ad $ad, EntityManagerInterface $manager){
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "Votre annonce <strong>{ $ad->getTitle() }</strong>  a bien ete supprimer"
        );

        return $this->redirectToRoute('voirs_annonces');

    }
   
}

templates/ad/_ad.html.twig
{% set url =  path('voir_annonce', {'slug':ad.slug}) %}
<div class="col-md-4 my-3">
			<div class="card" style="width:18rem;">
				<div class="card-header text-center">
					{{ad.rooms}} Chambre,<strong> {{ad.price}} FCFA/nuit</strong><br>
					{% if ad.comments | length > 0 %}
					{% include 'partiels/rating.html.twig' with {'rating': ad.avgRatings} %} <br>
					     <small> Calcule sur {{ ad.comments|length }} avis !</small>
					{% else %}
						<small>Pas d'avis !!!</small>	
					{% endif %}
					
						
					
				</div>
				<a href="{{url}}">
				<img src="{{ ad.coverImage }}" alt="image-avatar" class="float-left" style="width: 100%;
	              height:200px; display: block;">
				  </a>
				<div class="card-body">
				<a href="{{url}}">
					<h5 class="card-title">
					{{ad.title}}
					</h5>
				 </a>
					<p class="card-text">
						{{ad.introduction}}
					</p>
					<a href="{{url}}" class="btn btn-primary float-right">En savoir plus</a>
					{% if app.user and app.user == ad.getAuthor() %}
			        <a href="{{ path('edite_article',{'slug' :ad.slug})}}" class="btn btn-primary">modifier</a>
			        {% endif %}	
				</div>
			</div>
		</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
 <P>Ici vous pouvez ajoute l'image de la maison</P>
    {{ form_widget(form) }}
    
 
    <input type="hidden" id="widget-counters" value="0">
    <div class="form-group">
     <button type="button" id="add-image" class="btn btn-primary">
     <i class="fas fa-plus"></i>
     Ajouter une image</button>
    </div>
{% endblock %}
{% block _ad_images_entry_row %}
    {{ form_widget(form )}}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                    <div class="row">
                            <div class="col">
                                {{form_widget(form.url)}}
                                {{ form_errors(form.url) }}
                            </div>
                             <div class="col">
                                {{form_widget(form.legende)}}
                                {{ form_errors(form.legende) }}
                            </div>
                        </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="Delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
       
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}
{% block title %}Modification Maison{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}
{% block body %} 
<div class="container">
    <h1>Modifier l'annonce {{ad.title}} !!!</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Effectuez la modification !!</button>
    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
 
 <script src="/js/ad.js"></script>
 
    
 {% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
<div class="container">
<h2 class="my-5">Voici les annonces de nos hotes !!!</h2>
<div class="row">
{% for ad in ads %}
 {% include 'ad/_ad.html.twig' %}
{% endfor %}
	</div>	
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}
{% block title %}NOUVELLE Maison{% endblock %}
{% form_theme form 'ad/_collection.html.twig' %}
{% block body %} 
<div class="container">
    <h1 class="my-5">Créer une nouvelle annoncees !!!</h1>
    {{ form_start(form) }}
    <div class="row">
        <div class="col">
            <div class="alert alert-light">
            <h2>Informations génerales</h2>
            <hr>
            {{form_row(form.title)}}
            {{form_row(form.slug)}}
            {{form_row(form.price)}}
            {{form_row(form.rooms)}}
            <hr>
            {{form_row(form.introduction)}}
            {{form_row(form.content)}}
            </div>
        </div>
        <div class="col">
            <div class="alert alert-light">
                <h2>Images de l'annonces</h2>
                <hr>
                {{form_row(form.coverImage)}}
                {{form_row(form.images)}}
            </div>
        </div>
    </div>
    <div class="alert alert-success clearfix">
    <h2 class="alert-heading">Sauvegarder mon annonces</h2>
    <p>Vous êtes sur le point de créer votre annonce, nous sommes super fier de vous !!</p>
    
    <button type="submit" class="btn btn-primary float-right" >
    <i class="fas fa-check"></i>
    Creez la nouvelle annonces !!
    </button> </div>
    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
 
 <script src="/js/ad.js">
     
 </script>

 {% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{ ad.title }}
{% endblock %}
{% block body %}
	<div class="add-tittle" style="background-image : url({{ad.coverImage}})">
		<div class="container">
			<h1>{{ad.title}}</h1>
			<p>{{ad.introduction}}</p>
			<p><strong>{{ad.rooms}} Chambres </strong>pour <strong>{{ad.price | number_format(2,',', ' ')}}</strong> FCFA par nuits</p>
			<a href="{{ path('book_create',{'slug': ad.slug}) }}" class="btn btn-success">Reservez !!!</a>
			{% if app.user and app.user == ad.getAuthor() %}
			<a href="{{ path('edite_article',{'slug' :ad.slug}) }}" class="btn btn-primary">Modifier</a>
			<a href="{{ path('supprimer_article',{'slug' :ad.slug}) }}" class="btn btn-danger"
			onClick="return confirm(`vous voulez supprimer {{ad.title}}`)">Supprimer</a>
			{% endif %}
		</div>
		
	</div>
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				<h1>{{ad.content|raw}}</h1>
				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
					{% for images in ad.images %}
						<li data-target="#carouselExampleIndicators" data-slide-to="{{loop.index0}}" class="active"></li>
					{% endfor %}
					</ol>
					<div class="carousel-inner">
					{% for images in ad.images %}
						<div class="carousel-item {% if loop.first %} active  {% endif %} ">
							<img class="d-block w-100" src="{{images.url}}" alt="First slide">
						</div>
					{% endfor %}
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
				<hr>
				{% if ad.comments|length >0%}
					<h2 class="mb-3">Commentaires de nos voyageurs :</h2>
					<div class="alert alert-info">
						<h4 class="alert-heading">
							<div class="row align-items-center">
								<div class="col">
								  Note global donnée par nos voyageurs <br>   
								</div>
								<div class="col">
								{% include 'partiels/rating.html.twig' with {'rating': ad.avgRatings} %} <br>
								<small> Calcule sur {{ ad.comments|length }} avis !</small>

								</div>
							</div>
						</h4>
					</div>
					{% for comment in ad.comments %}
					<div class="bg-light rounded mb-3 py-3 px-3">
						<strong> {{ comment.author.fullname}}</strong> a dit :
						<blockquote>
						 {{comment.content}}
						</blockquote>
						<strong>Note donneé par {{ comment.author.fullname}} :</strong>{{comment.rating}}
						{% include 'partiels/rating.html.twig' with {'rating' : comment.rating} %}
						
					</div>
					{% endfor %}
				{% else %}
					<h2>Cette annonce n'a pas encore de commentaire</h2>
				{% endif %}
			</div>
			<div class="col">
			{% set a = ad.author %}
				<div class="row mb-3 align-items-center">
					<div class="col-3">
						<img class = "avatar avatar-medium" src="{{a.picture}}" alt="photo de {{a.fullname}}">
					</div>
					<div class="col">
						<h1>{{a.fullname()}}</h1>
						<span class="badge badge-primary">{{a.ads|length }} Annonces !!!</span>
					</div>
				</div>
				<p>{{a.description | raw}}</p>
			</div>
		</div>
	</div>
	
{% endblock %}